name: Minecraft Client Build

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Supaya bisa klik "Run" manual di web

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Gradle
      # Kita pake gradle langsung tanpa plugin setup-gradle buat bypass cache error
      run: |
        chmod +x gradlew || true
        ./gradlew build --no-daemon
